import image from './assets/cardImg.png';

type CardProps = {
  imgUrl: string;
  title: string;
  desc: string;
  price: number;
  bedrooms: number;
  bath: number;
  type: string;
  featured: boolean;
};

const homes: CardProps[] = [
  {
    imgUrl: `${image}`,
    title: 'Seaside serenity villa',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem, voluptatum doloribus sapiente id natus adipisci sunt soluta voluptas porro placeat nobis quod accusantium tempora iure iste officiis aperiam architecto quam atque suscipit? Et voluptas minima reprehenderit maxime nobis vel qui, inventore tenetur facilis, excepturi voluptatibus deserunt.',
    price: 2000,
    bedrooms: 4,
    bath: 3,
    type: 'Villa',
    featured: true,
  },
  {
    imgUrl: `${image}`,
    title: 'Seaside serenity villa',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem, voluptatum doloribus sapiente id natus adipisci sunt soluta voluptas porro placeat nobis quod accusantium tempora iure iste officiis aperiam architecto quam atque suscipit? Et voluptas minima reprehenderit maxime nobis vel qui, inventore tenetur facilis, excepturi voluptatibus deserunt.',
    price: 2000,
    bedrooms: 4,
    bath: 3,
    type: 'Villa',
    featured: true,
  },
  {
    imgUrl: `${image}`,
    title: 'Seaside serenity villa',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem, voluptatum doloribus sapiente id natus adipisci sunt soluta voluptas porro placeat nobis quod accusantium tempora iure iste officiis aperiam architecto quam atque suscipit? Et voluptas minima reprehenderit maxime nobis vel qui, inventore tenetur facilis, excepturi voluptatibus deserunt.',
    price: 2000,
    bedrooms: 4,
    bath: 3,
    type: 'Villa',
    featured: true,
  },
  {
    imgUrl: `${image}`,
    title: 'Seaside serenity villa',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem, voluptatum doloribus sapiente id natus adipisci sunt soluta voluptas porro placeat nobis quod accusantium tempora iure iste officiis aperiam architecto quam atque suscipit? Et voluptas minima reprehenderit maxime nobis vel qui, inventore tenetur facilis, excepturi voluptatibus deserunt.',
    price: 2000,
    bedrooms: 4,
    bath: 3,
    type: 'Villa',
    featured: true,
  },
  {
    imgUrl: `${image}`,
    title: 'Seaside serenity villa',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem, voluptatum doloribus sapiente id natus adipisci sunt soluta voluptas porro placeat nobis quod accusantium tempora iure iste officiis aperiam architecto quam atque suscipit? Et voluptas minima reprehenderit maxime nobis vel qui, inventore tenetur facilis, excepturi voluptatibus deserunt.',
    price: 2000,
    bedrooms: 4,
    bath: 3,
    type: 'Villa',
    featured: true,
  },
  {
    imgUrl: `${image}`,
    title: 'Seaside serenity villa',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem, voluptatum doloribus sapiente id natus adipisci sunt soluta voluptas porro placeat nobis quod accusantium tempora iure iste officiis aperiam architecto quam atque suscipit? Et voluptas minima reprehenderit maxime nobis vel qui, inventore tenetur facilis, excepturi voluptatibus deserunt.',
    price: 2000,
    bedrooms: 4,
    bath: 3,
    type: 'Villa',
    featured: true,
  },
  {
    imgUrl: `${image}`,
    title: 'Seaside serenity villa',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem, voluptatum doloribus sapiente id natus adipisci sunt soluta voluptas porro placeat nobis quod accusantium tempora iure iste officiis aperiam architecto quam atque suscipit? Et voluptas minima reprehenderit maxime nobis vel qui, inventore tenetur facilis, excepturi voluptatibus deserunt.',
    price: 2000,
    bedrooms: 4,
    bath: 3,
    type: 'Villa',
    featured: true,
  },
  {
    imgUrl: `${image}`,
    title: 'Seaside serenity villa',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem, voluptatum doloribus sapiente id natus adipisci sunt soluta voluptas porro placeat nobis quod accusantium tempora iure iste officiis aperiam architecto quam atque suscipit? Et voluptas minima reprehenderit maxime nobis vel qui, inventore tenetur facilis, excepturi voluptatibus deserunt.',
    price: 2000,
    bedrooms: 4,
    bath: 3,
    type: 'Villa',
    featured: true,
  },
  {
    imgUrl: `${image}`,
    title: 'Seaside serenity villa',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem, voluptatum doloribus sapiente id natus adipisci sunt soluta voluptas porro placeat nobis quod accusantium tempora iure iste officiis aperiam architecto quam atque suscipit? Et voluptas minima reprehenderit maxime nobis vel qui, inventore tenetur facilis, excepturi voluptatibus deserunt.',
    price: 2000,
    bedrooms: 4,
    bath: 3,
    type: 'Villa',
    featured: false,
  },
  {
    imgUrl: `${image}`,
    title: 'Seaside serenity villa',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem, voluptatum doloribus sapiente id natus adipisci sunt soluta voluptas porro placeat nobis quod accusantium tempora iure iste officiis aperiam architecto quam atque suscipit? Et voluptas minima reprehenderit maxime nobis vel qui, inventore tenetur facilis, excepturi voluptatibus deserunt.',
    price: 2000,
    bedrooms: 4,
    bath: 3,
    type: 'Villa',
    featured: false,
  },
  {
    imgUrl: `${image}`,
    title: 'Seaside serenity villa',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem, voluptatum doloribus sapiente id natus adipisci sunt soluta voluptas porro placeat nobis quod accusantium tempora iure iste officiis aperiam architecto quam atque suscipit? Et voluptas minima reprehenderit maxime nobis vel qui, inventore tenetur facilis, excepturi voluptatibus deserunt.',
    price: 2000,
    bedrooms: 4,
    bath: 3,
    type: 'Villa',
    featured: false,
  },
  {
    imgUrl: `${image}`,
    title: 'Seaside serenity villa',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem, voluptatum doloribus sapiente id natus adipisci sunt soluta voluptas porro placeat nobis quod accusantium tempora iure iste officiis aperiam architecto quam atque suscipit? Et voluptas minima reprehenderit maxime nobis vel qui, inventore tenetur facilis, excepturi voluptatibus deserunt.',
    price: 2000,
    bedrooms: 4,
    bath: 3,
    type: 'Villa',
    featured: false,
  },
  {
    imgUrl: `${image}`,
    title: 'Seaside serenity villa',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem, voluptatum doloribus sapiente id natus adipisci sunt soluta voluptas porro placeat nobis quod accusantium tempora iure iste officiis aperiam architecto quam atque suscipit? Et voluptas minima reprehenderit maxime nobis vel qui, inventore tenetur facilis, excepturi voluptatibus deserunt.',
    price: 2000,
    bedrooms: 4,
    bath: 3,
    type: 'Villa',
    featured: false,
  },
  {
    imgUrl: `${image}`,
    title: 'Seaside serenity villa',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem, voluptatum doloribus sapiente id natus adipisci sunt soluta voluptas porro placeat nobis quod accusantium tempora iure iste officiis aperiam architecto quam atque suscipit? Et voluptas minima reprehenderit maxime nobis vel qui, inventore tenetur facilis, excepturi voluptatibus deserunt.',
    price: 2000,
    bedrooms: 4,
    bath: 3,
    type: 'Villa',
    featured: false,
  },
  {
    imgUrl: `${image}`,
    title: 'Seaside serenity villa',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem, voluptatum doloribus sapiente id natus adipisci sunt soluta voluptas porro placeat nobis quod accusantium tempora iure iste officiis aperiam architecto quam atque suscipit? Et voluptas minima reprehenderit maxime nobis vel qui, inventore tenetur facilis, excepturi voluptatibus deserunt.',
    price: 2000,
    bedrooms: 4,
    bath: 3,
    type: 'Villa',
    featured: false,
  },
  {
    imgUrl: `${image}`,
    title: 'Seaside serenity villa',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem, voluptatum doloribus sapiente id natus adipisci sunt soluta voluptas porro placeat nobis quod accusantium tempora iure iste officiis aperiam architecto quam atque suscipit? Et voluptas minima reprehenderit maxime nobis vel qui, inventore tenetur facilis, excepturi voluptatibus deserunt.',
    price: 2000,
    bedrooms: 4,
    bath: 3,
    type: 'Villa',
    featured: false,
  },
  {
    imgUrl: `${image}`,
    title: 'Seaside serenity villa',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem, voluptatum doloribus sapiente id natus adipisci sunt soluta voluptas porro placeat nobis quod accusantium tempora iure iste officiis aperiam architecto quam atque suscipit? Et voluptas minima reprehenderit maxime nobis vel qui, inventore tenetur facilis, excepturi voluptatibus deserunt.',
    price: 2000,
    bedrooms: 4,
    bath: 3,
    type: 'Villa',
    featured: false,
  },
  {
    imgUrl: `${image}`,
    title: 'Seaside serenity villa',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem, voluptatum doloribus sapiente id natus adipisci sunt soluta voluptas porro placeat nobis quod accusantium tempora iure iste officiis aperiam architecto quam atque suscipit? Et voluptas minima reprehenderit maxime nobis vel qui, inventore tenetur facilis, excepturi voluptatibus deserunt.',
    price: 2000,
    bedrooms: 4,
    bath: 3,
    type: 'Villa',
    featured: false,
  },
  {
    imgUrl: `${image}`,
    title: 'Seaside serenity villa',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem, voluptatum doloribus sapiente id natus adipisci sunt soluta voluptas porro placeat nobis quod accusantium tempora iure iste officiis aperiam architecto quam atque suscipit? Et voluptas minima reprehenderit maxime nobis vel qui, inventore tenetur facilis, excepturi voluptatibus deserunt.',
    price: 2000,
    bedrooms: 4,
    bath: 3,
    type: 'Villa',
    featured: false,
  },
  {
    imgUrl: `${image}`,
    title: 'Seaside serenity villa',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem, voluptatum doloribus sapiente id natus adipisci sunt soluta voluptas porro placeat nobis quod accusantium tempora iure iste officiis aperiam architecto quam atque suscipit? Et voluptas minima reprehenderit maxime nobis vel qui, inventore tenetur facilis, excepturi voluptatibus deserunt.',
    price: 2000,
    bedrooms: 4,
    bath: 3,
    type: 'Villa',
    featured: false,
  },
  {
    imgUrl: `${image}`,
    title: 'Seaside serenity villa',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem, voluptatum doloribus sapiente id natus adipisci sunt soluta voluptas porro placeat nobis quod accusantium tempora iure iste officiis aperiam architecto quam atque suscipit? Et voluptas minima reprehenderit maxime nobis vel qui, inventore tenetur facilis, excepturi voluptatibus deserunt.',
    price: 2000,
    bedrooms: 4,
    bath: 3,
    type: 'Villa',
    featured: false,
  },
  {
    imgUrl: `${image}`,
    title: 'Seaside serenity villa',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem, voluptatum doloribus sapiente id natus adipisci sunt soluta voluptas porro placeat nobis quod accusantium tempora iure iste officiis aperiam architecto quam atque suscipit? Et voluptas minima reprehenderit maxime nobis vel qui, inventore tenetur facilis, excepturi voluptatibus deserunt.',
    price: 2000,
    bedrooms: 4,
    bath: 3,
    type: 'Villa',
    featured: false,
  },
];

export { homes };
